// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // CLI-команды (migrate/db push/studio) используют схема-движок Prisma,
  // который ходит напрямую в базу, в обход PgBouncer (см. .env, docs/adr/0009).
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
